# Generated by Django 4.0.5 on 2022-09-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='diognoses',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='prescriptions',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
